// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/codec.dart';
import 'api/inspect.dart';
import 'api/metadata.dart';
import 'api/region.dart';
import 'api/simple.dart';
import 'api/verify.dart';
import 'dart:async';
import 'dart:convert';
import 'engine/codec.dart';
import 'engine/codec/heif_alpha.dart';
import 'engine/format.dart';
import 'engine/inspect.dart';
import 'engine/metadata.dart';
import 'engine/verify.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class DarkLib extends BaseEntrypoint<DarkLibApi, DarkLibApiImpl, DarkLibWire> {
  @internal
  static final instance = DarkLib._();

  DarkLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    DarkLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required DarkLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<DarkLibApiImpl, DarkLibWire> get apiImplConstructor =>
      DarkLibApiImpl.new;

  @override
  WireConstructor<DarkLibWire> get wireConstructor =>
      DarkLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 92172621;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'darklib',
        ioDirectory: 'native/darklib/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class DarkLibApi extends BaseApi {
  int crateApiRegionRegionReaderHeight({required RegionReader that});

  Future<RegionReader> crateApiRegionRegionReaderOpen({
    required String path,
    required String cacheDir,
  });

  Future<List<RegionTile>> crateApiRegionRegionReaderTiles({
    required RegionReader that,
    required List<int> rect,
    required List<int> cuts,
    required int sample,
  });

  int crateApiRegionRegionReaderWidth({required RegionReader that});

  Future<AlphaKept> crateApiVerifyAlphaKept({
    required List<int> source,
    required List<int> output,
  });

  bool crateApiMetadataCanStripLossless({required List<int> bytes});

  String crateApiSimpleDarklibVersion();

  FormatInfo crateApiMetadataDescribeFormat({required List<int> bytes});

  ImageFormat crateApiMetadataDetectFormat({required List<int> bytes});

  Future<Uint8List> crateApiCodecFlattenOnWhite({required List<int> bytes});

  String crateApiSimpleGreet({required String name});

  Future<AlphaStream?> crateApiCodecHeifAlphaStream({required List<int> bytes});

  Future<Uint8List> crateApiCodecHeifAttachAlpha({
    required List<int> source,
    required List<int> base,
    required List<int> grey,
  });

  Future<void> crateApiSimpleInitApp();

  Future<Facts> crateApiInspectInspectImage({required List<int> bytes});

  Future<Uint8List> crateApiCodecJpegReencode({
    required List<int> bytes,
    required int quality,
  });

  Future<ProfileSpace?> crateApiInspectProfileSpace({required List<int> bytes});

  MetadataSummary crateApiMetadataReadMetadataSummary({
    required List<int> bytes,
  });

  Future<Uint8List> crateApiMetadataStripMetadata({
    required List<int> bytes,
    required bool stripIcc,
  });

  Future<Transcoded> crateApiCodecTranscode({
    required List<int> bytes,
    required CodecFormat format,
    required int quality,
    required int maxEdge,
    required bool keepMetadata,
    required int bitDepth,
  });

  Future<Transplanted> crateApiMetadataTransplantMetadata({
    required List<int> source,
    required List<int> target,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RegionReader;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RegionReader;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RegionReaderPtr;
}

class DarkLibApiImpl extends DarkLibApiImplPlatform implements DarkLibApi {
  DarkLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int crateApiRegionRegionReaderHeight({required RegionReader that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRegionRegionReaderHeightConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRegionRegionReaderHeightConstMeta =>
      const TaskConstMeta(debugName: "RegionReader_height", argNames: ["that"]);

  @override
  Future<RegionReader> crateApiRegionRegionReaderOpen({
    required String path,
    required String cacheDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(cacheDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRegionRegionReaderOpenConstMeta,
        argValues: [path, cacheDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRegionRegionReaderOpenConstMeta =>
      const TaskConstMeta(
        debugName: "RegionReader_open",
        argNames: ["path", "cacheDir"],
      );

  @override
  Future<List<RegionTile>> crateApiRegionRegionReaderTiles({
    required RegionReader that,
    required List<int> rect,
    required List<int> cuts,
    required int sample,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
            that,
            serializer,
          );
          sse_encode_list_prim_u_32_loose(rect, serializer);
          sse_encode_list_prim_u_32_loose(cuts, serializer);
          sse_encode_u_32(sample, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_region_tile,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRegionRegionReaderTilesConstMeta,
        argValues: [that, rect, cuts, sample],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRegionRegionReaderTilesConstMeta =>
      const TaskConstMeta(
        debugName: "RegionReader_tiles",
        argNames: ["that", "rect", "cuts", "sample"],
      );

  @override
  int crateApiRegionRegionReaderWidth({required RegionReader that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRegionRegionReaderWidthConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRegionRegionReaderWidthConstMeta =>
      const TaskConstMeta(debugName: "RegionReader_width", argNames: ["that"]);

  @override
  Future<AlphaKept> crateApiVerifyAlphaKept({
    required List<int> source,
    required List<int> output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(source, serializer);
          sse_encode_list_prim_u_8_loose(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_alpha_kept,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVerifyAlphaKeptConstMeta,
        argValues: [source, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyAlphaKeptConstMeta => const TaskConstMeta(
    debugName: "alpha_kept",
    argNames: ["source", "output"],
  );

  @override
  bool crateApiMetadataCanStripLossless({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataCanStripLosslessConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataCanStripLosslessConstMeta =>
      const TaskConstMeta(debugName: "can_strip_lossless", argNames: ["bytes"]);

  @override
  String crateApiSimpleDarklibVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDarklibVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDarklibVersionConstMeta =>
      const TaskConstMeta(debugName: "darklib_version", argNames: []);

  @override
  FormatInfo crateApiMetadataDescribeFormat({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_format_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataDescribeFormatConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataDescribeFormatConstMeta =>
      const TaskConstMeta(debugName: "describe_format", argNames: ["bytes"]);

  @override
  ImageFormat crateApiMetadataDetectFormat({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_format,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataDetectFormatConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataDetectFormatConstMeta =>
      const TaskConstMeta(debugName: "detect_format", argNames: ["bytes"]);

  @override
  Future<Uint8List> crateApiCodecFlattenOnWhite({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCodecFlattenOnWhiteConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCodecFlattenOnWhiteConstMeta =>
      const TaskConstMeta(debugName: "flatten_on_white", argNames: ["bytes"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<AlphaStream?> crateApiCodecHeifAlphaStream({
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_alpha_stream,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCodecHeifAlphaStreamConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCodecHeifAlphaStreamConstMeta =>
      const TaskConstMeta(debugName: "heif_alpha_stream", argNames: ["bytes"]);

  @override
  Future<Uint8List> crateApiCodecHeifAttachAlpha({
    required List<int> source,
    required List<int> base,
    required List<int> grey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(source, serializer);
          sse_encode_list_prim_u_8_loose(base, serializer);
          sse_encode_list_prim_u_8_loose(grey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCodecHeifAttachAlphaConstMeta,
        argValues: [source, base, grey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCodecHeifAttachAlphaConstMeta =>
      const TaskConstMeta(
        debugName: "heif_attach_alpha",
        argNames: ["source", "base", "grey"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Facts> crateApiInspectInspectImage({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_facts,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInspectInspectImageConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectInspectImageConstMeta =>
      const TaskConstMeta(debugName: "inspect_image", argNames: ["bytes"]);

  @override
  Future<Uint8List> crateApiCodecJpegReencode({
    required List<int> bytes,
    required int quality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_u_32(quality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCodecJpegReencodeConstMeta,
        argValues: [bytes, quality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCodecJpegReencodeConstMeta => const TaskConstMeta(
    debugName: "jpeg_reencode",
    argNames: ["bytes", "quality"],
  );

  @override
  Future<ProfileSpace?> crateApiInspectProfileSpace({
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_profile_space,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInspectProfileSpaceConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectProfileSpaceConstMeta =>
      const TaskConstMeta(debugName: "profile_space", argNames: ["bytes"]);

  @override
  MetadataSummary crateApiMetadataReadMetadataSummary({
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataReadMetadataSummaryConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataReadMetadataSummaryConstMeta =>
      const TaskConstMeta(
        debugName: "read_metadata_summary",
        argNames: ["bytes"],
      );

  @override
  Future<Uint8List> crateApiMetadataStripMetadata({
    required List<int> bytes,
    required bool stripIcc,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_bool(stripIcc, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMetadataStripMetadataConstMeta,
        argValues: [bytes, stripIcc],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataStripMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "strip_metadata",
        argNames: ["bytes", "stripIcc"],
      );

  @override
  Future<Transcoded> crateApiCodecTranscode({
    required List<int> bytes,
    required CodecFormat format,
    required int quality,
    required int maxEdge,
    required bool keepMetadata,
    required int bitDepth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_codec_format(format, serializer);
          sse_encode_u_32(quality, serializer);
          sse_encode_u_32(maxEdge, serializer);
          sse_encode_bool(keepMetadata, serializer);
          sse_encode_u_32(bitDepth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcoded,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCodecTranscodeConstMeta,
        argValues: [bytes, format, quality, maxEdge, keepMetadata, bitDepth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCodecTranscodeConstMeta => const TaskConstMeta(
    debugName: "transcode",
    argNames: [
      "bytes",
      "format",
      "quality",
      "maxEdge",
      "keepMetadata",
      "bitDepth",
    ],
  );

  @override
  Future<Transplanted> crateApiMetadataTransplantMetadata({
    required List<int> source,
    required List<int> target,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(source, serializer);
          sse_encode_list_prim_u_8_loose(target, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transplanted,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataTransplantMetadataConstMeta,
        argValues: [source, target],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataTransplantMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "transplant_metadata",
        argNames: ["source", "target"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RegionReader => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RegionReader => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader;

  @protected
  RegionReader
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RegionReaderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RegionReader
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RegionReaderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RegionReader
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RegionReaderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AlphaKept dco_decode_alpha_kept(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AlphaKept.values[raw as int];
  }

  @protected
  AlphaStream dco_decode_alpha_stream(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AlphaStream(
      hevc: dco_decode_list_prim_u_8_strict(arr[0]),
      frames: dco_decode_u_32(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AlphaStream dco_decode_box_autoadd_alpha_stream(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_alpha_stream(raw);
  }

  @protected
  ProfileSpace dco_decode_box_autoadd_profile_space(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_profile_space(raw);
  }

  @protected
  CodecFormat dco_decode_codec_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CodecFormat.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Facts dco_decode_facts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Facts(
      transfer: dco_decode_transfer(arr[0]),
      gainMap: dco_decode_presence(arr[1]),
      alpha: dco_decode_presence(arr[2]),
      width: dco_decode_u_32(arr[3]),
      height: dco_decode_u_32(arr[4]),
      orientation: dco_decode_u_8(arr[5]),
      bitDepth: dco_decode_u_8(arr[6]),
    );
  }

  @protected
  FormatInfo dco_decode_format_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FormatInfo(
      format: dco_decode_image_format(arr[0]),
      supportsExif: dco_decode_bool(arr[1]),
      supportsXmp: dco_decode_bool(arr[2]),
      supportsIcc: dco_decode_bool(arr[3]),
      supportsIptc: dco_decode_bool(arr[4]),
      hdrCapable: dco_decode_bool(arr[5]),
      canStrip: dco_decode_bool(arr[6]),
    );
  }

  @protected
  HdrOutcome dco_decode_hdr_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HdrOutcome.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImageFormat dco_decode_image_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImageFormat.values[raw as int];
  }

  @protected
  List<MetaKind> dco_decode_list_meta_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_meta_kind).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RegionTile> dco_decode_list_region_tile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_region_tile).toList();
  }

  @protected
  MetaKind dco_decode_meta_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MetaKind.values[raw as int];
  }

  @protected
  MetadataSummary dco_decode_metadata_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MetadataSummary(
      hasExif: dco_decode_bool(arr[0]),
      hasXmp: dco_decode_bool(arr[1]),
      hasIcc: dco_decode_bool(arr[2]),
      hasGps: dco_decode_bool(arr[3]),
      hasDate: dco_decode_bool(arr[4]),
      hasCamera: dco_decode_bool(arr[5]),
      orientation: dco_decode_u_16(arr[6]),
      tagCount: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  AlphaStream? dco_decode_opt_box_autoadd_alpha_stream(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_alpha_stream(raw);
  }

  @protected
  ProfileSpace? dco_decode_opt_box_autoadd_profile_space(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_profile_space(raw);
  }

  @protected
  Presence dco_decode_presence(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Presence.values[raw as int];
  }

  @protected
  ProfileSpace dco_decode_profile_space(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProfileSpace(
      toXyzD50: dco_decode_list_prim_f_32_strict(arr[0]),
      transfer: dco_decode_list_prim_f_32_strict(arr[1]),
    );
  }

  @protected
  RegionTile dco_decode_region_tile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RegionTile(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  Transcoded dco_decode_transcoded(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Transcoded(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      hdr: dco_decode_hdr_outcome(arr[1]),
      dropped: dco_decode_list_meta_kind(arr[2]),
    );
  }

  @protected
  Transfer dco_decode_transfer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Transfer.values[raw as int];
  }

  @protected
  Transplanted dco_decode_transplanted(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Transplanted(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      dropped: dco_decode_list_meta_kind(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  RegionReader
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RegionReaderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RegionReader
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RegionReaderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RegionReader
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RegionReaderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AlphaKept sse_decode_alpha_kept(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AlphaKept.values[inner];
  }

  @protected
  AlphaStream sse_decode_alpha_stream(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hevc = sse_decode_list_prim_u_8_strict(deserializer);
    var var_frames = sse_decode_u_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return AlphaStream(
      hevc: var_hevc,
      frames: var_frames,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AlphaStream sse_decode_box_autoadd_alpha_stream(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_alpha_stream(deserializer));
  }

  @protected
  ProfileSpace sse_decode_box_autoadd_profile_space(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_profile_space(deserializer));
  }

  @protected
  CodecFormat sse_decode_codec_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CodecFormat.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  Facts sse_decode_facts(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transfer = sse_decode_transfer(deserializer);
    var var_gainMap = sse_decode_presence(deserializer);
    var var_alpha = sse_decode_presence(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_orientation = sse_decode_u_8(deserializer);
    var var_bitDepth = sse_decode_u_8(deserializer);
    return Facts(
      transfer: var_transfer,
      gainMap: var_gainMap,
      alpha: var_alpha,
      width: var_width,
      height: var_height,
      orientation: var_orientation,
      bitDepth: var_bitDepth,
    );
  }

  @protected
  FormatInfo sse_decode_format_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_format = sse_decode_image_format(deserializer);
    var var_supportsExif = sse_decode_bool(deserializer);
    var var_supportsXmp = sse_decode_bool(deserializer);
    var var_supportsIcc = sse_decode_bool(deserializer);
    var var_supportsIptc = sse_decode_bool(deserializer);
    var var_hdrCapable = sse_decode_bool(deserializer);
    var var_canStrip = sse_decode_bool(deserializer);
    return FormatInfo(
      format: var_format,
      supportsExif: var_supportsExif,
      supportsXmp: var_supportsXmp,
      supportsIcc: var_supportsIcc,
      supportsIptc: var_supportsIptc,
      hdrCapable: var_hdrCapable,
      canStrip: var_canStrip,
    );
  }

  @protected
  HdrOutcome sse_decode_hdr_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return HdrOutcome.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImageFormat sse_decode_image_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImageFormat.values[inner];
  }

  @protected
  List<MetaKind> sse_decode_list_meta_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MetaKind>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_meta_kind(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RegionTile> sse_decode_list_region_tile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RegionTile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_region_tile(deserializer));
    }
    return ans_;
  }

  @protected
  MetaKind sse_decode_meta_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MetaKind.values[inner];
  }

  @protected
  MetadataSummary sse_decode_metadata_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hasExif = sse_decode_bool(deserializer);
    var var_hasXmp = sse_decode_bool(deserializer);
    var var_hasIcc = sse_decode_bool(deserializer);
    var var_hasGps = sse_decode_bool(deserializer);
    var var_hasDate = sse_decode_bool(deserializer);
    var var_hasCamera = sse_decode_bool(deserializer);
    var var_orientation = sse_decode_u_16(deserializer);
    var var_tagCount = sse_decode_u_32(deserializer);
    return MetadataSummary(
      hasExif: var_hasExif,
      hasXmp: var_hasXmp,
      hasIcc: var_hasIcc,
      hasGps: var_hasGps,
      hasDate: var_hasDate,
      hasCamera: var_hasCamera,
      orientation: var_orientation,
      tagCount: var_tagCount,
    );
  }

  @protected
  AlphaStream? sse_decode_opt_box_autoadd_alpha_stream(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_alpha_stream(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileSpace? sse_decode_opt_box_autoadd_profile_space(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_profile_space(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Presence sse_decode_presence(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Presence.values[inner];
  }

  @protected
  ProfileSpace sse_decode_profile_space(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_toXyzD50 = sse_decode_list_prim_f_32_strict(deserializer);
    var var_transfer = sse_decode_list_prim_f_32_strict(deserializer);
    return ProfileSpace(toXyzD50: var_toXyzD50, transfer: var_transfer);
  }

  @protected
  RegionTile sse_decode_region_tile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return RegionTile(width: var_width, height: var_height, rgba: var_rgba);
  }

  @protected
  Transcoded sse_decode_transcoded(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_hdr = sse_decode_hdr_outcome(deserializer);
    var var_dropped = sse_decode_list_meta_kind(deserializer);
    return Transcoded(bytes: var_bytes, hdr: var_hdr, dropped: var_dropped);
  }

  @protected
  Transfer sse_decode_transfer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Transfer.values[inner];
  }

  @protected
  Transplanted sse_decode_transplanted(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_dropped = sse_decode_list_meta_kind(deserializer);
    return Transplanted(bytes: var_bytes, dropped: var_dropped);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    RegionReader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RegionReaderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    RegionReader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RegionReaderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegionReader(
    RegionReader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RegionReaderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_alpha_kept(AlphaKept self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_alpha_stream(AlphaStream self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.hevc, serializer);
    sse_encode_u_32(self.frames, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_alpha_stream(
    AlphaStream self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_alpha_stream(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_profile_space(
    ProfileSpace self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_profile_space(self, serializer);
  }

  @protected
  void sse_encode_codec_format(CodecFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_facts(Facts self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transfer(self.transfer, serializer);
    sse_encode_presence(self.gainMap, serializer);
    sse_encode_presence(self.alpha, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_8(self.orientation, serializer);
    sse_encode_u_8(self.bitDepth, serializer);
  }

  @protected
  void sse_encode_format_info(FormatInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_format(self.format, serializer);
    sse_encode_bool(self.supportsExif, serializer);
    sse_encode_bool(self.supportsXmp, serializer);
    sse_encode_bool(self.supportsIcc, serializer);
    sse_encode_bool(self.supportsIptc, serializer);
    sse_encode_bool(self.hdrCapable, serializer);
    sse_encode_bool(self.canStrip, serializer);
  }

  @protected
  void sse_encode_hdr_outcome(HdrOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_image_format(ImageFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_meta_kind(
    List<MetaKind> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_meta_kind(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(
      self is Uint32List ? self : Uint32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_region_tile(
    List<RegionTile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_region_tile(item, serializer);
    }
  }

  @protected
  void sse_encode_meta_kind(MetaKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_metadata_summary(
    MetadataSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.hasExif, serializer);
    sse_encode_bool(self.hasXmp, serializer);
    sse_encode_bool(self.hasIcc, serializer);
    sse_encode_bool(self.hasGps, serializer);
    sse_encode_bool(self.hasDate, serializer);
    sse_encode_bool(self.hasCamera, serializer);
    sse_encode_u_16(self.orientation, serializer);
    sse_encode_u_32(self.tagCount, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_alpha_stream(
    AlphaStream? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_alpha_stream(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_profile_space(
    ProfileSpace? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_profile_space(self, serializer);
    }
  }

  @protected
  void sse_encode_presence(Presence self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_profile_space(ProfileSpace self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_32_strict(self.toXyzD50, serializer);
    sse_encode_list_prim_f_32_strict(self.transfer, serializer);
  }

  @protected
  void sse_encode_region_tile(RegionTile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_transcoded(Transcoded self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_hdr_outcome(self.hdr, serializer);
    sse_encode_list_meta_kind(self.dropped, serializer);
  }

  @protected
  void sse_encode_transfer(Transfer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transplanted(Transplanted self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_list_meta_kind(self.dropped, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class RegionReaderImpl extends RustOpaque implements RegionReader {
  // Not to be used by end users
  RegionReaderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RegionReaderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        DarkLib.instance.api.rust_arc_increment_strong_count_RegionReader,
    rustArcDecrementStrongCount:
        DarkLib.instance.api.rust_arc_decrement_strong_count_RegionReader,
    rustArcDecrementStrongCountPtr:
        DarkLib.instance.api.rust_arc_decrement_strong_count_RegionReaderPtr,
  );

  /// Upright height.
  int get height =>
      DarkLib.instance.api.crateApiRegionRegionReaderHeight(that: this);

  /// The upright rectangle `rect` = `[left, top, right, bottom)` sampled
  /// down by `sample` (a power of two), cut at the upright x positions
  /// `cuts` into tiles, left to right.
  Future<List<RegionTile>> tiles({
    required List<int> rect,
    required List<int> cuts,
    required int sample,
  }) => DarkLib.instance.api.crateApiRegionRegionReaderTiles(
    that: this,
    rect: rect,
    cuts: cuts,
    sample: sample,
  );

  /// Upright width.
  int get width =>
      DarkLib.instance.api.crateApiRegionRegionReaderWidth(that: this);
}
