// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The alpha plane's coded frames, ready for an HEVC decoder.
class AlphaStream {
  /// Annex-B HEVC: each frame's parameter sets, then its picture.
  final Uint8List hevc;

  /// One frame per tile, in row-major tile order.
  final int frames;

  /// Size of every frame; the decoded grey output is `frames × width × height`
  /// bytes.
  final int width;
  final int height;

  const AlphaStream({
    required this.hevc,
    required this.frames,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      hevc.hashCode ^ frames.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlphaStream &&
          runtimeType == other.runtimeType &&
          hevc == other.hevc &&
          frames == other.frames &&
          width == other.width &&
          height == other.height;
}
