#!/usr/bin/env python3
"""Generates Hayn's app icon for iOS and Android from one geometry.

The mark: crop handles on a thin frame around a mountain-and-sun photo, white
on the accent gradient (lib/app/theme/design_tokens.dart). Everything below
derives from the GLYPH constants, drawn on Apple's 1024 icon canvas.

Outputs, overwritten in place:
  ios/Runner/Assets.xcassets/AppIcon.appiconset
      Light (opaque), Dark and Tinted (transparent — iOS supplies the plate)
  android/app/src/main/res
      adaptive icon: vector background + foreground; the white-only
      foreground doubles as the Android 13 monochrome layer
      legacy PNG mipmaps for API 24-25 (minSdk 24)
  docs/brand/hayn-icon.png
      the README header mark, clipped to iOS's icon shape

Needs Google Chrome (renders the SVGs) and Xcode's swift (png_tool.swift).
Usage: python3 tool/app_icon/generate.py
"""

import json
import math
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

# ── Glyph (1024 canvas) ────────────────────────────────────────────────────
SCALE = 1.22  # grows the mark about the centre so it fills the icon

FRAME = "M248,248H776V776H248Z"  # thin frame, stroked
FRAME_WIDTH = 16
HANDLES = ("M248,372V248H372", "M652,248H776V372",
           "M776,652V776H652", "M372,776H248V652")
HANDLE_WIDTH = 46
SUN = (598, 420, 50)
MOUNTAIN = ("M338,684L448,548Q468,524 488,548L566,644L604,600"
            "Q622,580 640,600L686,652V684H338Z")
MOUNTAIN_ROUNDING = 22  # same-colour stroke that rounds the mountain's corners

# Farthest point from the centre (unscaled): a handle's corner plus half its
# stroke.
GLYPH_RADIUS = (512 - 248) * math.sqrt(2) + HANDLE_WIDTH / 2

# ── Colours ────────────────────────────────────────────────────────────────
PLATE = ("#5B8DF8", "#1D4ED8")      # accentDark-ish top → accentLight bottom
DARK_GLYPH = ("#9DBBFC", "#4F86F7")  # on iOS's own dark plate
FRAME_OPACITY = 0.38

# ── Android ────────────────────────────────────────────────────────────────
# Adaptive icons draw on 108dp; any launcher mask keeps a 66dp circle.
ANDROID_SAFE_RADIUS = 33
ANDROID_SCALE = ANDROID_SAFE_RADIUS / GLYPH_RADIUS
LEGACY_SIZES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}

GENERATED = "Generated by tool/app_icon/generate.py — edit the script, not this file."


def sun_path(cx, cy, r):
    return f"M{cx - r},{cy}a{r},{r} 0 1,0 {2 * r},0a{r},{r} 0 1,0 {-2 * r},0"


def glyph_svg(fg, frame_color):
    handles = "".join(f'<path d="{d}"/>' for d in HANDLES)
    cx, cy, r = SUN
    return f"""
  <g transform="translate(512 512) scale({SCALE}) translate(-512 -512)">
    <path d="{FRAME}" fill="none" stroke="{frame_color}"
          stroke-opacity="{FRAME_OPACITY}" stroke-width="{FRAME_WIDTH}"/>
    <g fill="none" stroke="{fg}" stroke-width="{HANDLE_WIDTH}"
       stroke-linecap="round" stroke-linejoin="round">{handles}</g>
    <circle cx="{cx}" cy="{cy}" r="{r}" fill="{fg}"/>
    <path d="{MOUNTAIN}" fill="{fg}" stroke="{fg}"
          stroke-width="{MOUNTAIN_ROUNDING}" stroke-linejoin="round"/>
  </g>"""


def icon_svg(*, plate, fg, frame_color, clip_rx=None):
    """plate: gradient stops or None (transparent). fg: colour or stops."""
    defs, fill = [], fg
    if plate:
        defs.append(f"""<linearGradient id="plate" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{plate[0]}"/><stop offset="1" stop-color="{plate[1]}"/>
    </linearGradient>""")
    if isinstance(fg, tuple):
        # User space so every part of the mark shares one gradient.
        defs.append(f"""<linearGradient id="glyph" gradientUnits="userSpaceOnUse"
        x1="0" y1="200" x2="0" y2="824">
      <stop offset="0" stop-color="{fg[0]}"/><stop offset="1" stop-color="{fg[1]}"/>
    </linearGradient>""")
        fill = "url(#glyph)"
    clip = ""
    if clip_rx is not None:
        defs.append(f'<clipPath id="shape"><rect x="40" y="40" width="944" '
                    f'height="944" rx="{clip_rx}"/></clipPath>')
        clip = ' clip-path="url(#shape)"'
    plate_rect = '<rect width="1024" height="1024" fill="url(#plate)"/>' if plate else ""
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <defs>{''.join(defs)}</defs>
  <g{clip}>{plate_rect}{glyph_svg(fill, frame_color)}</g>
</svg>"""


def render(svg, out_png, work):
    page = work / (out_png.stem + ".html")
    page.write_text(
        "<!doctype html><html><head><style>html,body{margin:0;background:transparent}"
        "svg{display:block;width:100vw;height:100vh}</style></head><body>"
        f"{svg}</body></html>", encoding="utf-8")
    subprocess.run(
        [CHROME, "--headless=new", "--disable-gpu", "--hide-scrollbars",
         "--force-device-scale-factor=1", "--default-background-color=00000000",
         "--window-size=1024,1024", f"--screenshot={out_png}", page.as_uri()],
        check=True, capture_output=True)
    if not out_png.exists():
        raise SystemExit(f"Chrome did not render {out_png.name}")


def png_tool(src, dst, size, mode):
    """mode: opaque (no alpha channel), alpha, or ios-mask (iOS icon shape)."""
    subprocess.run(["xcrun", "swift", str(HERE / "png_tool.swift"),
                    str(src), str(dst), str(size), mode], check=True)


def generate_ios(work):
    iconset = ROOT / "ios/Runner/Assets.xcassets/AppIcon.appiconset"
    variants = {
        # name: (appearance, svg, opaque)
        "AppIcon-Light.png": (None, icon_svg(plate=PLATE, fg="#FFFFFF", frame_color="#FFFFFF"), True),
        "AppIcon-Dark.png": ("dark", icon_svg(plate=None, fg=DARK_GLYPH, frame_color=DARK_GLYPH[1]), False),
        "AppIcon-Tinted.png": ("tinted", icon_svg(plate=None, fg="#FFFFFF", frame_color="#FFFFFF"), False),
    }
    images = []
    for name, (appearance, svg, opaque) in variants.items():
        raw = work / f"ios-{name}"
        render(svg, raw, work)
        png_tool(raw, iconset / name, 1024, "opaque" if opaque else "alpha")
        entry = {"filename": name, "idiom": "universal", "platform": "ios", "size": "1024x1024"}
        if appearance:
            entry = {"appearances": [{"appearance": "luminosity", "value": appearance}], **entry}
        images.append(entry)
    # The set is owned by this script: drop images it no longer references.
    for stale in iconset.glob("*.png"):
        if stale.name not in variants:
            stale.unlink()
    (iconset / "Contents.json").write_text(
        json.dumps({"images": images, "info": {"author": "xcode", "version": 1}}, indent=2) + "\n")


def vector_foreground():
    # Maps the unscaled glyph's radius onto the safe circle; SCALE is iOS-only.
    k = round(ANDROID_SCALE, 5)
    white = "#FFFFFFFF"
    handles = "\n".join(
        f'      <path android:pathData="{d}" android:strokeColor="{white}" '
        f'android:strokeWidth="{HANDLE_WIDTH}" android:strokeLineCap="round" '
        f'android:strokeLineJoin="round"/>' for d in HANDLES)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {GENERATED} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <group android:translateX="54" android:translateY="54" android:scaleX="{k}" android:scaleY="{k}">
    <group android:translateX="-512" android:translateY="-512">
      <path android:pathData="{FRAME}" android:strokeColor="{white}" android:strokeAlpha="{FRAME_OPACITY}" android:strokeWidth="{FRAME_WIDTH}"/>
{handles}
      <path android:pathData="{sun_path(*SUN)}" android:fillColor="{white}"/>
      <path android:pathData="{MOUNTAIN}" android:fillColor="{white}" android:strokeColor="{white}" android:strokeWidth="{MOUNTAIN_ROUNDING}" android:strokeLineJoin="round"/>
    </group>
  </group>
</vector>
"""


def vector_background():
    def argb(hex_rgb):
        return "#FF" + hex_rgb.lstrip("#").upper()

    # The gradient spans the visible 72dp, matching the iOS plate.
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {GENERATED} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <path android:pathData="M0,0h108v108h-108z">
    <aapt:attr name="android:fillColor">
      <gradient android:type="linear" android:startX="0" android:startY="18"
          android:endX="0" android:endY="90"
          android:startColor="{argb(PLATE[0])}" android:endColor="{argb(PLATE[1])}"/>
    </aapt:attr>
  </path>
</vector>
"""


ADAPTIVE = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {GENERATED} -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@drawable/ic_launcher_background"/>
  <foreground android:drawable="@drawable/ic_launcher_foreground"/>
  <monochrome android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
"""


def generate_android(work):
    res = ROOT / "android/app/src/main/res"
    (res / "drawable/ic_launcher_foreground.xml").write_text(vector_foreground(), encoding="utf-8")
    (res / "drawable/ic_launcher_background.xml").write_text(vector_background(), encoding="utf-8")
    (res / "mipmap-anydpi-v26").mkdir(exist_ok=True)
    (res / "mipmap-anydpi-v26/ic_launcher.xml").write_text(ADAPTIVE, encoding="utf-8")

    # API 24-25 launchers show the bitmap as-is: a rounded square on the
    # standard 2/48 inset, with transparent corners.
    raw = work / "android-legacy.png"
    render(icon_svg(plate=PLATE, fg="#FFFFFF", frame_color="#FFFFFF", clip_rx=210), raw, work)
    for density, size in LEGACY_SIZES.items():
        png_tool(raw, res / f"mipmap-{density}/ic_launcher.png", size, "alpha")


def generate_readme_mark(work):
    # The light icon in iOS's own shape, for the README header (shown at 92pt).
    raw = work / "readme.png"
    render(icon_svg(plate=PLATE, fg="#FFFFFF", frame_color="#FFFFFF"), raw, work)
    (ROOT / "docs/brand").mkdir(parents=True, exist_ok=True)
    png_tool(raw, ROOT / "docs/brand/hayn-icon.png", 276, "ios-mask")


def main():
    if not Path(CHROME).exists():
        raise SystemExit(f"Google Chrome not found at {CHROME}")
    work = Path(tempfile.mkdtemp(prefix="hayn-icon-"))
    try:
        generate_ios(work)
        generate_android(work)
        generate_readme_mark(work)
    finally:
        shutil.rmtree(work, ignore_errors=True)
    print("App icon generated for iOS and Android.")


if __name__ == "__main__":
    main()
