// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/codec.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `target_of`

/// Decode → optional downscale → encode at `quality` (1..=100; PNG ignores it).
/// `keep_metadata` carries EXIF/XMP/ICC. The result says what happened to an
/// HDR gain map. Throws `preservation_required:…` for PQ/HLG, which this
/// engine cannot render correctly as SDR, and a plain message for containers
/// the codec layer can't handle.
Future<Transcoded> transcode({
  required List<int> bytes,
  required CodecFormat format,
  required int quality,
  required int maxEdge,
  required bool keepMetadata,
}) => DarkLib.instance.api.crateApiCodecTranscode(
  bytes: bytes,
  format: format,
  quality: quality,
  maxEdge: maxEdge,
  keepMetadata: keepMetadata,
);

/// Target encode format for [`transcode`].
enum CodecFormat { jpeg, png, webp, webpLossless, avif }
