// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/codec.dart';
import '../engine/codec/heif_alpha.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `target_of`

/// Opaque, upright PNG of `bytes` over white, for a JPEG of a transparent
/// source. Throws on a container the codec cannot decode, or past the budget.
Future<Uint8List> flattenOnWhite({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiCodecFlattenOnWhite(bytes: bytes);

/// Decode → optional downscale → encode at `quality` (1..=100; PNG ignores it).
/// `keep_metadata` carries EXIF/XMP/ICC. The result says what happened to an
/// HDR gain map. Throws `preservation_required:…` for PQ/HLG, which this
/// engine cannot render correctly as SDR, and a plain message for containers
/// the codec layer can't handle.
Future<Transcoded> transcode({
  required List<int> bytes,
  required CodecFormat format,
  required int quality,
  required int maxEdge,
  required bool keepMetadata,
}) => DarkLib.instance.api.crateApiCodecTranscode(
  bytes: bytes,
  format: format,
  quality: quality,
  maxEdge: maxEdge,
  keepMetadata: keepMetadata,
);

/// The alpha plane of a HEIF image's primary item as an Annex-B HEVC stream,
/// one frame per tile, for an HEVC decoder outside DarkLib; `None` when the
/// image has no alpha. Throws on HEIF whose alpha it cannot lay out (Hayn
/// IMG-15: Android's HEIF decoder drops the plane).
Future<AlphaStream?> heifAlphaStream({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiCodecHeifAlphaStream(bytes: bytes);

/// `base` (the platform's upright decode of `source`) with `grey`, the
/// stream's frames decoded to 8-bit full-range grey, as its alpha: an RGBA
/// PNG. Throws when the plane does not fit the image.
Future<Uint8List> heifAttachAlpha({
  required List<int> source,
  required List<int> base,
  required List<int> grey,
}) => DarkLib.instance.api.crateApiCodecHeifAttachAlpha(
  source: source,
  base: base,
  grey: grey,
);

/// Target encode format for [`transcode`].
enum CodecFormat { jpeg, png, webp, webpLossless, avif }
