// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Decode → optional downscale (long edge ≤ `max_edge`; 0 = keep original size)
/// → encode to `format` at `quality` (1..=100; ignored for PNG). Throws on a
/// container the codec layer can't handle yet.
Future<Uint8List> transcode({
  required List<int> bytes,
  required CodecFormat format,
  required int quality,
  required int maxEdge,
}) => DarkLib.instance.api.crateApiCodecTranscode(
  bytes: bytes,
  format: format,
  quality: quality,
  maxEdge: maxEdge,
);

/// Target encode format for [`transcode`].
enum CodecFormat { jpeg, png, webp, webpLossless, avif }
