// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/inspect.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// HDR facts of `bytes`: the primary image's transfer (PQ/HLG) and whether a
/// gain map is present. Unreadable containers answer `Unknown`.
Future<Facts> inspectImage({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiInspectInspectImage(bytes: bytes);
