// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/format.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `can_strip_format`

/// Detect the container from leading bytes. Pure + fast → sync.
ImageFormat detectFormat({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiMetadataDetectFormat(bytes: bytes);

/// Describe the container's metadata abilities (capability matrix for the UI).
FormatInfo describeFormat({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiMetadataDescribeFormat(bytes: bytes);

/// Whether DarkLib can strip this container's metadata losslessly today.
bool canStripLossless({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiMetadataCanStripLossless(bytes: bytes);

/// Strip metadata losslessly (no re-encode). `strip_icc` also removes the ICC
/// colour profile (default false = colour-safe); the orientation tag is always
/// kept so the image can't flip. Throws on an unsupported container. Runs off
/// the Dart isolate.
Future<Uint8List> stripMetadata({
  required List<int> bytes,
  required bool stripIcc,
}) => DarkLib.instance.api.crateApiMetadataStripMetadata(
  bytes: bytes,
  stripIcc: stripIcc,
);

/// What a container can carry + whether DarkLib can strip it losslessly today
/// (`can_strip` drives UI capability gating without a second call).
class FormatInfo {
  final ImageFormat format;
  final bool supportsExif;
  final bool supportsXmp;
  final bool supportsIcc;
  final bool supportsIptc;
  final bool hdrCapable;
  final bool canStrip;

  const FormatInfo({
    required this.format,
    required this.supportsExif,
    required this.supportsXmp,
    required this.supportsIcc,
    required this.supportsIptc,
    required this.hdrCapable,
    required this.canStrip,
  });

  @override
  int get hashCode =>
      format.hashCode ^
      supportsExif.hashCode ^
      supportsXmp.hashCode ^
      supportsIcc.hashCode ^
      supportsIptc.hashCode ^
      hdrCapable.hashCode ^
      canStrip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          supportsExif == other.supportsExif &&
          supportsXmp == other.supportsXmp &&
          supportsIcc == other.supportsIcc &&
          supportsIptc == other.supportsIptc &&
          hdrCapable == other.hdrCapable &&
          canStrip == other.canStrip;
}
