// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/format.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `can_strip_format`

/// Detect the container from leading bytes. Pure + fast → sync.
ImageFormat detectFormat({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiMetadataDetectFormat(bytes: bytes);

/// Describe the container's metadata abilities (capability matrix for the UI).
FormatInfo describeFormat({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiMetadataDescribeFormat(bytes: bytes);

/// Whether DarkLib can strip this container's metadata losslessly today.
bool canStripLossless({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiMetadataCanStripLossless(bytes: bytes);

/// Strip metadata losslessly (no re-encode). `strip_icc` also removes the ICC
/// colour profile (default false = colour-safe); the orientation tag is always
/// kept so the image can't flip. Throws on an unsupported container. Runs off
/// the Dart isolate.
Future<Uint8List> stripMetadata({
  required List<int> bytes,
  required bool stripIcc,
}) => DarkLib.instance.api.crateApiMetadataStripMetadata(
  bytes: bytes,
  stripIcc: stripIcc,
);

/// Copy `source`'s metadata (EXIF/XMP/ICC, kept verbatim) into the
/// already-encoded `target` — e.g. carry camera metadata into a hardware
/// encoder's AVIF output, which the platform encoder itself can't do. Lossless
/// container surgery on `target`; returns `target` unchanged when nothing can
/// be carried safely (the verify-or-bail rule). Runs off the Dart isolate.
Future<Uint8List> transplantMetadata({
  required List<int> source,
  required List<int> target,
}) => DarkLib.instance.api.crateApiMetadataTransplantMetadata(
  source: source,
  target: target,
);

/// Summarise the metadata present in an image. Cheap container scan → sync.
MetadataSummary readMetadataSummary({required List<int> bytes}) =>
    DarkLib.instance.api.crateApiMetadataReadMetadataSummary(bytes: bytes);

/// What a container can carry + whether DarkLib can strip it losslessly today
/// (`can_strip` drives UI capability gating without a second call).
class FormatInfo {
  final ImageFormat format;
  final bool supportsExif;
  final bool supportsXmp;
  final bool supportsIcc;
  final bool supportsIptc;
  final bool hdrCapable;
  final bool canStrip;

  const FormatInfo({
    required this.format,
    required this.supportsExif,
    required this.supportsXmp,
    required this.supportsIcc,
    required this.supportsIptc,
    required this.hdrCapable,
    required this.canStrip,
  });

  @override
  int get hashCode =>
      format.hashCode ^
      supportsExif.hashCode ^
      supportsXmp.hashCode ^
      supportsIcc.hashCode ^
      supportsIptc.hashCode ^
      hdrCapable.hashCode ^
      canStrip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          supportsExif == other.supportsExif &&
          supportsXmp == other.supportsXmp &&
          supportsIcc == other.supportsIcc &&
          supportsIptc == other.supportsIptc &&
          hdrCapable == other.hdrCapable &&
          canStrip == other.canStrip;
}

/// What metadata an image carries — for the "what will be removed" preview.
/// Works cross-platform (incl. HEIC/AVIF), unlike `package:exif` on Android.
class MetadataSummary {
  final bool hasExif;
  final bool hasXmp;
  final bool hasIcc;
  final bool hasGps;
  final bool hasDate;
  final bool hasCamera;

  /// EXIF orientation (1..=8; 1 = upright).
  final int orientation;
  final int tagCount;

  const MetadataSummary({
    required this.hasExif,
    required this.hasXmp,
    required this.hasIcc,
    required this.hasGps,
    required this.hasDate,
    required this.hasCamera,
    required this.orientation,
    required this.tagCount,
  });

  @override
  int get hashCode =>
      hasExif.hashCode ^
      hasXmp.hashCode ^
      hasIcc.hashCode ^
      hasGps.hashCode ^
      hasDate.hashCode ^
      hasCamera.hashCode ^
      orientation.hashCode ^
      tagCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataSummary &&
          runtimeType == other.runtimeType &&
          hasExif == other.hasExif &&
          hasXmp == other.hasXmp &&
          hasIcc == other.hasIcc &&
          hasGps == other.hasGps &&
          hasDate == other.hasDate &&
          hasCamera == other.hasCamera &&
          orientation == other.orientation &&
          tagCount == other.tagCount;
}
