// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RegionReader>>
abstract class RegionReader implements RustOpaqueInterface {
  /// Upright height.
  int get height;

  /// Reads the AVIF at `path` (the caller may delete it once this returns)
  /// and prepares it: a grid decodes one cell, one item is decoded whole
  /// into raw files under `cache_dir`. Throws for anything but an SDR AVIF
  /// whose colours convert to sRGB here, and past the decode budget.
  static Future<RegionReader> open({
    required String path,
    required String cacheDir,
  }) => DarkLib.instance.api.crateApiRegionRegionReaderOpen(
    path: path,
    cacheDir: cacheDir,
  );

  /// The upright rectangle `rect` = `[left, top, right, bottom)` sampled
  /// down by `sample` (a power of two), cut at the upright x positions
  /// `cuts` into tiles, left to right.
  Future<List<RegionTile>> tiles({
    required List<int> rect,
    required List<int> cuts,
    required int sample,
  });

  /// Upright width.
  int get width;
}

/// A decoded tile: premultiplied 8-bit RGBA, row-major (what Flutter's
/// `rgba8888` takes).
class RegionTile {
  final int width;
  final int height;
  final Uint8List rgba;

  const RegionTile({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegionTile &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}
