// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Round-trips a string across the FFI boundary. Used by the smoke test.
String greet({required String name}) =>
    DarkLib.instance.api.crateApiSimpleGreet(name: name);

/// The DarkLib core version (the crate's Cargo version), so the Dart side can
/// assert the bundled native library matches the bindings it was generated for.
String darklibVersion() => DarkLib.instance.api.crateApiSimpleDarklibVersion();
