// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/verify.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Whether `output` keeps the transparency of `source`, from decoded alpha
/// values rather than channel presence (Hayn IMG-15).
Future<AlphaKept> alphaKept({
  required List<int> source,
  required List<int> output,
}) => DarkLib.instance.api.crateApiVerifyAlphaKept(
  source: source,
  output: output,
);
