// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'metadata.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What a transcode did with an HDR gain map. The HDR policy (user decision,
/// 2026-09-28): keep HDR where the path is proven, otherwise encode the SDR
/// base without asking. The caller records anything but `None`/`GainMapKept`.
/// Keeping is proven by ImageIO reading the rebuilt ISO gain map (IMG-10).
enum HdrOutcome {
  /// No gain map was recognised in the source.
  none,

  /// The gain map was rebuilt next to the re-encoded base.
  gainMapKept,

  /// The target, resize or orientation cannot carry it; SDR base only.
  gainMapDropped,

  /// Keeping was attempted and failed; SDR base only.
  gainMapKeepFailed,
}

class Transcoded {
  final Uint8List bytes;
  final HdrOutcome hdr;

  /// The metadata kinds the source held that the output could not (Hayn
  /// RV-04): the caller records them.
  final List<MetaKind> dropped;

  const Transcoded({
    required this.bytes,
    required this.hdr,
    required this.dropped,
  });

  @override
  int get hashCode => bytes.hashCode ^ hdr.hashCode ^ dropped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Transcoded &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          hdr == other.hdr &&
          dropped == other.dropped;
}
