// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What a transcode did with an HDR gain map. The HDR policy (user decision,
/// 2026-09-28): keep HDR where the path is proven, otherwise encode the SDR
/// base without asking. The caller records anything but `None`/`GainMapKept`.
///
/// `GainMapKept`/`GainMapKeepFailed` are not produced today: the AVIF writer
/// (`isobmff::build_hdr_avif`) is not recognised by an independent reader
/// (ImageIO sees no gain map: no `tmap` brand, missing `tmap` properties, pixi
/// ≠ av1C depth). Hayn IMG-09/IMG-10 re-enable keeping once it is verified.
enum HdrOutcome {
  /// No gain map was recognised in the source.
  none,

  /// The gain map was rebuilt next to the re-encoded base.
  gainMapKept,

  /// The target, resize, orientation or an unverified writer cannot carry
  /// it; SDR base only.
  gainMapDropped,

  /// Keeping was attempted and failed; SDR base only.
  gainMapKeepFailed,
}

class Transcoded {
  final Uint8List bytes;
  final HdrOutcome hdr;

  const Transcoded({required this.bytes, required this.hdr});

  @override
  int get hashCode => bytes.hashCode ^ hdr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Transcoded &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          hdr == other.hdr;
}
