// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Image container, detected from leading magic bytes. Mirrors the set the app
/// already recognises (`SniffedFormat` in Dart), so behaviour is unchanged when
/// the live code migrates onto DarkLib.
enum ImageFormat { jpeg, png, webp, gif, bmp, tiff, heic, avif, unknown }
