// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Facts {
  final Transfer transfer;
  final Presence gainMap;
  final Presence alpha;

  /// Stored size from the header (for HEIF/AVIF the primary item or its
  /// grid canvas), before orientation; 0 when the header does not say.
  final int width;
  final int height;

  /// EXIF-style orientation (1..=8) that turns the stored pixels upright:
  /// `irot`/`imir` for HEIF/AVIF (their EXIF tag is not what readers
  /// apply), the EXIF tag otherwise. 0 when the file names none (upright).
  final int orientation;

  /// Bits per channel as stored (8, 10, 12, 16), from the container: HEIF/
  /// AVIF `pixi` or coding configuration, PNG `IHDR`, JPEG `SOF`; WebP is
  /// 8. 0 when the header does not say. What "match the source" means for
  /// the user's bit-depth choice (Hayn IMG-23).
  final int bitDepth;

  const Facts({
    required this.transfer,
    required this.gainMap,
    required this.alpha,
    required this.width,
    required this.height,
    required this.orientation,
    required this.bitDepth,
  });

  @override
  int get hashCode =>
      transfer.hashCode ^
      gainMap.hashCode ^
      alpha.hashCode ^
      width.hashCode ^
      height.hashCode ^
      orientation.hashCode ^
      bitDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Facts &&
          runtimeType == other.runtimeType &&
          transfer == other.transfer &&
          gainMap == other.gainMap &&
          alpha == other.alpha &&
          width == other.width &&
          height == other.height &&
          orientation == other.orientation &&
          bitDepth == other.bitDepth;
}

enum Presence { unknown, absent, present }

/// Transfer function of the primary image.
enum Transfer {
  unknown,
  noHdrSignal,

  /// SMPTE ST 2084 (transfer_characteristics 16).
  pq,

  /// ARIB STD-B67 (transfer_characteristics 18).
  hlg,
}
