// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Facts {
  final Transfer transfer;
  final Presence gainMap;

  const Facts({required this.transfer, required this.gainMap});

  @override
  int get hashCode => transfer.hashCode ^ gainMap.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Facts &&
          runtimeType == other.runtimeType &&
          transfer == other.transfer &&
          gainMap == other.gainMap;
}

enum Presence { unknown, absent, present }

/// Transfer function of the primary image.
enum Transfer {
  unknown,
  noHdrSignal,

  /// SMPTE ST 2084 (transfer_characteristics 16).
  pq,

  /// ARIB STD-B67 (transfer_characteristics 18).
  hlg,
}
